### ISSUE TITLE
[FEATURE]: Migrate `spark.table("db.table")` to `spark.table("catalog.db.table")`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Every table in UC needs a catalog

### Proposed Solution

Transform AST/CST with the migrated table index using the fixer framework declared in https://github.com/databrickslabs/ucx/pull/1067

- `spark.table(...)`
- `spark.read.table(...)`
- `...write.saveAsTable(...)`
- ...

Add another Linter/Fixer to https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/code/pyspark.py

**Comment by ericvergnaud** [comment]
@nfs Resonating on the conversation we had re _runtime analysis_ vs _static analysis_...
Re the former, we can refine between _pre_ and _post_ analysis. 
My understanding is that customers are expected to test the migration in their testing environment.
Is it fare to assume that implementing a post-migration analyzer in a testing environment would be easier to get approved than a pre-migration analyzer in production ?
If so, such post-migration analyzer would be a wonderful opportunity to collect actual names of DB or FS objects causing problems. We could then enrich our static analysis with these names in order to detect not only the calling patterns (which is what we currently plan to do), but also value patterns.

**Comment by ericvergnaud** [comment]
As the list of candidate function calls eligible to migration grows, our currently minimalistic approach (checking just the name and arguments of the function being called) might increase the risk of unwanted migrations.
Also, if the argument is not a string literal, the migration will be skipped.
Is that something we want to cater for, and if it is, should it be done as part of this ticket ?

**Comment by nfx** [comment]
> As the list of candidate function calls eligible to migration grows, our currently minimalistic approach (checking just the name and arguments of the function being called) might increase the risk of unwanted migrations.

that's correct.

> Also, if the argument is not a string literal, the migration will be skipped.

please create an issue to do value inference and let's leave it out of scope for this ticket for now. We may bring more external dependencies for this, like `astroid` or `libcst`, but the initial working solution may be implemented without those.

**Comment by nfx** [comment]
@jimidle ^

**Comment by ericvergnaud** [comment]
@jimidle you could leverage what I did for sys.path in PythonLinter once it's merged to main - fyi @nfx

**Comment by jimidle** [comment]
> @jimidle you could leverage what I did for sys.path in PythonLinter once it's merged to main - fyi @nfx

OK - I will take a look once you merge it. @nfx Do you have a preference for using the fixer framework over Eric's suggestion?

**Comment by ericvergnaud** [comment]
My suggestion is for improved linting, not for fixing. It's now merged

**Comment by nfx** [comment]
@jimidle @ericvergnaud sys.path manipulation and this feature are orthogonal. We already have the fixer framework and the example is with sql queries. 

The implementation that only looks at string constants is trivial and should not take more than few hours to implement and test.

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/pull/1210
