### ISSUE TITLE
[BUG]: estimates_report run  fails on non uc enabled workspaces

### ISSUE THREAD

**Issue by rkkalluri** [databrickslabs/ucx#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looks like this is a new task added to UCX assessment and it fails when workspace is not uc enabled

### Expected Behavior

UCX assessment is mostly run before a metastore is assigned in general cases. We should provide an option to make this optional or skip it if workspace is not uc enabled.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
@rkkalluri insufficient information. need logs to further diagnose.

**Comment by mohanab-db** [comment]
@nfx I have also seen the same issue. The assessment task estimates_report fails if a metastore is not assigned to the workspace. This task is refreshing a dashboard 'UCX] UCX Assessment (Estimates)'. Only one query fails.
`SELECT case when CURRENT_METASTORE() is not null then "Metastore already assigned" else "Metastore not assigned" end as uc_metastore_assigned
`
That's because the inbuilt function CURRENT_METASTORE() (instead of returning null, which the code is expecting) throws an error if a metastore is not assigned.
`[OPERATION_REQUIRES_UNITY_CATALOG] Operation CURRENT_METASTORE requires Unity Catalog enabled.
`
SQL file path - /ucx/src/databricks/labs/ucx/queries/assessment/estimates/00_2_is_metastore_assigned.sql
<img width="1087" alt="image" src="https://github.com/databrickslabs/ucx/assets/121183444/985ef19b-85f6-414b-96dd-2735b8df4625">

**Comment by qziyuan** [comment]
There is not a good solution for a DBSQL query to tell if the workspace is UC enabled or not. For now we have to bear with this error, but the document should be improved to notice this behavior.

**Comment by nfx** [comment]
@ericvergnaud nouc-workspace is `labs-azure-admin` (via labs CLI)

**Comment by rkkalluri** [comment]
What roles are expected in Azure subscriptions by these ucx commands. It is
better to document them instead of arriving by trial and error. Hopefully
it is not global admin as that is not a reality in the enterprise.

**Comment by ericvergnaud** [comment]
@rkkalluri I'm looking to fix this issue, but there seems to be quite a gap between this thread and the latest code since the above problematic query is no longer available in the code base. I'm wondering if this bug might already be fixed ? Can you check ?

**Comment by ericvergnaud** [comment]
@rkkalluri any update ? Or should we close this issue ?

**Comment by rkkalluri** [comment]
We can close this, it seems to be fixed at the moment

**Comment by ericvergnaud** [comment]
Thanks @rkkalluri
