### ISSUE TITLE
[BUG]: Uninstallation of UCX fails stating "warehouse not found"

### ISSUE THREAD

**Issue by anurag2541992** [databrickslabs/ucx#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Uninstallation of UCX is failing stating warehouse not found. If a warehouse created during installation of UCX has been deleted from the workspace, the uninstallation of UCX should not fail and should allow me to reinstall UCX.

### Expected Behavior

The uninstallation of UCX should not fail and should allow me to reinstall UCX.

### Steps To Reproduce

1: Attempt installation of UCX using databricks labs install ucx from Databricks CLI.
2: Installation fails for some reason midway.
3: Delete the warehouse created by the installation 
4: Attempt to uninstall/force uninstall UCX using databricks labs uninstall ucx.
5: Uninstallation fails stating: databricks.sdk.errors.platform.NotFound: The warehouse <warehouseid> was not found.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\sdk\core.py", line 238, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.NotFound: The warehouse 1c419929a853c89b was not found.
Error: uninstall hook: exit status 1
```

**Comment by JCZuurmond** [comment]
@anurag2541992 : Thank you for creating this bug. I am able to reproduce the error. However, would like to confirm the expected behavior with you:

The warehouse is needed for uninstalling ucx, for example to drop the database and tables created by ucx. Therefore, we need to (re)create the warehouse. Would you expect a prompt for this? Or did you have something else in mind?

**Comment by JCZuurmond** [comment]
A warehouse can not be recreated using the same ID. However, we can request again (how) to create a warehouse, like during the installation. Then the warehouse will be used for uninstalling the resources like the database and tables. Finally, the new warehouse will be deleted at the end of the unstallation process

**Comment by anurag2541992** [comment]
Thanks @JCZuurmond for the clarification. Please let me know if you have an ETA for this defect.

**Comment by anurag2541992** [comment]
@nfx - Has the bug been closed and ca UCX be uninstalled using 'databricks labs uninstall ucx'

**Comment by anurag2541992** [comment]
@nfx , @JCZuurmond  - Please confirm if the bug has been closed and I can install UCX again using 'databricks labs uninstall ucx'

**Comment by JCZuurmond** [comment]
Hi @anurag2541992 , a new version is released before the weekend. Could you try to uninstall with the newest version? You might need to run `databricks labs install ucx` first, before uninstalling. The install probably fails due to the missing warehouse, but just run it, then run the uninstall which should pass now
