### ISSUE TITLE
[BUG]: Upgrade from 0.16 to latest has error 'No module named 'databricks.labs.lsql'

### ISSUE THREAD

**Issue by harlankad-db** [databrickslabs/ucx#1743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running databricks.exe labs upgrade ucx on Windows, Molina first gets message that two Databricks CLIs were found, so it will use the latest. Then the script outputs the error in this bug title.

![image](https://github.com/databrickslabs/ucx/assets/100950447/4401ca1c-e7c6-4ca3-8ae3-8ea58895acc1)

### Expected Behavior

Upgrade should install any missing modules and or provide instructions to do so.

### Steps To Reproduce

1. In Windows, open a linux emulator, in this case, Mingw64
2. With UCX 0.16 previously installed, run databricks.exe labs upgrade ucx

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
@harlankad-db : thank you for opening the bug. In the second command, what is being run? 

In any case, it is worthwhile deleting the older Databricks cli and make sure you are able to upgrade ucx without any warning. It might be that the library is not found, because it is looking at the wrong location for dependencies via the other executable.

**Comment by nfx** [comment]
@harlankad-db fixed in CLI v0.218.1 - https://github.com/databricks/cli/releases/tag/v0.218.1
