### ISSUE TITLE
[BUG]: create-table-mapping fails for unsuccesful sync-workspace-info attemps

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This scenario happens when the Account Admin SP used does not have access on any Workspaces, and result in sync-workspace-info yielding an empty JSON file.
Because of this, create-table-mapping cannot do anything

![Capture d’écran 2024-05-24 à 14 13 56](https://github.com/databrickslabs/ucx/assets/107417584/791280aa-c36a-4f58-bd9e-0b29826b93b6)

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by william-conti** [comment]
After digging around, the workspaces.json looks like this

```
[
  {
    "account_id": "accounid",
    "azure_workspace_info": {
      "resource_group": "xxxx",
      "subscription_id": "xxx"
    },
    "creation_time": 1710514976458,
    "deployment_name": "adb-dddd.4",
    "location": "westeurope",
    "pricing_tier": "PREMIUM",
    "workspace_id": dddd,
    "workspace_name": "ps-west-europe-databricks",
    "workspace_status": "RUNNING",
    "workspace_status_message": "Workspace is running."
  },
  {
    "account_id": "accounid",
    "azure_workspace_info": {
      "resource_group": "eee",
      "subscription_id": "xxx"
    },
    "creation_time": 1702627279958,
    "deployment_name": "adb-ffff.10",
    "location": "northeurope",
    "pricing_tier": "PREMIUM",
    "workspace_id": ffff,
    "workspace_name": "g-dbr",
    "workspace_status": "RUNNING",
    "workspace_status_message": "Workspace is running."
  },
  {
    "account_id": "accounid",
    "azure_workspace_info": {
      "resource_group": "fe",
      "subscription_id": "xxx"
    },
    "creation_time": 1702887504474,
    "deployment_name": "adb-yyy.10",
    "location": "northeurope",
    "pricing_tier": "PREMIUM",
    "workspace_id": yyy,
    "workspace_name": "williamc_ucx",
    "workspace_status": "RUNNING",
    "workspace_status_message": "Workspace is running."
  }
]
```

But for some reason it cannot be read by the code

**Comment by pritishpai** [comment]
The above issue is occurring because a SP is used
`14:25:04  INFO [databricks.sdk] Using Azure CLI authentication with AAD tokens
14:25:04 DEBUG [databricks.sdk] GET /login?next_url=/api/2.0/preview/scim/v2/Me
< 200 OK
< [non-JSON document of 4702 bytes]
14:25:04 ERROR [d.l.ucx.create-table-mapping] Failed to call create-table-mapping: Traceback (most recent call last):
  File "/Users/pritish.pai/projects/ucx/.venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`


14:25:04 DEBUG [databricks.sdk] GET /login?next_url=/api/2.0/preview/scim/v2/Me
< 200 OK
< [non-JSON document of 4702 bytes]

**Comment by pritishpai** [comment]
I tried manually calling '/api/2.0/preview/scim/v2/Me' with the SP credentials and I did get back a valid JSON. 

@william-conti Can you please re-run the cli command with '--debug' and check if it is failing for you during the API call?
