### ISSUE TITLE
[BUG]: `register` triggers too many false positives

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, if we lint local code or add new known libraries, a lot of false positives appear in reports:
```
      {
        "code": "table-migrate",
        "message": "Can't migrate 'register' because its table name argument is not a constant"
      },
```

### Expected Behavior

Improve detection logic to trigger warnings only on spark-related code

### Steps To Reproduce

in ucx codebase:
1. `rm src/databricks/labs/ucx/source_code/known.json`
2. `make known`
3. view the contents of known.json file and seek false positives

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by asnare** [comment]
Currently `make known` fails if `known.json` cannot be opened or it doesn't contain a valid JSON object; to reproduce as the first step use:
1. `echo {} > src/databricks/labs/ucx/source_code/known.json`

**Comment by asnare** [comment]
I've been digging into this a bit, and something that I noticed is that the tests for this functionality are around [here](https://github.com/databrickslabs/ucx/blob/c88c981215c6013f81411997781ad33b68b0d668/tests/unit/source_code/test_pyspark.py#L104). It looks to me like there are quite a few bugs in the tests for these methods because of the methods being tested only one (`.table(str)`) is on the Spark context: the rest are elsewhere (a mix of the catalog, UDF and dataframe methods).
