### ISSUE TITLE
[BUG]: Should skip running TACL migration for workspaces without Table Access Control enabled

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we're getting `Couldn't fetch grants for object DATABASE hive_metastore.XXX: An error occurred while calling 0374.sql: org.apache.spark.SparkException: Trying to perform permission action on Hive Metastore /CATALOG/'hive _metastore'/DATABASE/'XXX' but Table Access Control is not enabled on this cluster.` even though we must not get any errors during assessment.

### Expected Behavior

no errors

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
In order to reproduce this issue, according to [these docs](https://learn.microsoft.com/en-us/azure/databricks/data-governance/table-acls/table-acl#python-and-sql-table-access-control), we need not only a workspace without TABLE_ACL, but also a cluster without TABLE_ACL. 
The docs explain how to turn TABLE_ACL on/off for a workspace, but not for a cluster... and I couldn't identify a way to do that via the UI (under "Compute"). It seems this setting can only be configured when creating the cluster ?

**Comment by ericvergnaud** [comment]
Regardless of the above, fetching the setting via `ws.workspace_conf.get_status(keys="enableAclsConfig")` fails with invalid key error.
Plus that might not tell us whether the cluster supports TABLE_ACL...
Switching to 'skip on error' strategy.
