### ISSUE TITLE
Assessment job is failing

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#227]
Crawl_grants failed - https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#job/18199892189402/run/506412567934467

inventorize_permissions run failed - https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#job/18199892189402/run/24279516544513

Hence the run for group migration failed - https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#job/638238974753091/run/32059274875612

**Comment by william-conti** [comment]
crawl_grants has failed because of this table -> hive_metastore.messages_prod.nest
It seem anyway that this table is completly broken anyway, we cannot read it and we cannot do much on it

![Capture d’écran 2023-09-20 à 09 29 22](https://github.com/databrickslabs/ucx/assets/107417584/02f6788c-9d6c-41b5-a2cd-a39592aba299)

**Comment by nfx** [comment]
@dipankarkush-db **Don't post internal environment links to public repositories!!!**

Instead, post the error message of the failure and the relevant context

**Comment by william-conti** [comment]
inventorize permission has failed because it is trying to list a path that looks like this:

`/Users/user_email@xxx.com/Rapid Start - DGP - 27/02`

This folder does exist in the workspace and in the Databrick UI, the `Rapid Start - DGP - 27/02`  is actually a single folder and not two folders. 

I guess that the workspace sdk doesn't handle well this kind of special paths

**Comment by nfx** [comment]
https://github.com/databrickslabs/ucx/issues/229

**Comment by nfx** [comment]
created https://github.com/databrickslabs/ucx/issues/230

**Comment by nfx** [comment]
created https://github.com/databrickslabs/ucx/issues/232

**Comment by nfx** [comment]
closing this issue in favor of more specific issues. @dipankarkush-db please see the examples of linked issues and create new ones about one single problem per issue the next time.

**Comment by dipankarkush-db** [comment]
Thanks @nfx
