### ISSUE TITLE
[FEATURE] Set `RemoveAfter` property on `ucx` catalogs in integration test

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2594]
### Summary

 Set `RemoveAfter` property on `ucx` catalogs create in integration tests using the [`make_catalog` fixture](https://github.com/databrickslabs/ucx/blob/6a6f2f4dd2f3c37878dd3596a0ed202859afa650/src/databricks/labs/ucx/mixins/fixtures.py#L972) to avoid watchdog deleting them too early, thus creating flaky integration tests. See example: https://github.com/databrickslabs/ucx/blob/6a6f2f4dd2f3c37878dd3596a0ed202859afa650/src/databricks/labs/ucx/mixins/fixtures.py#L1084

**Comment by asnare** [comment]
The Watchdog should ([and does](
https://github.com/databrickslabs/watchdog/blob/cdc97afdac1567e89d3b39d938f066fd6267b3ba/scan/objects/uc.go#L68)) cover catalogs, but at the moment it doesn't support any way to protect a (temporary fixture) catalog from being purged while a test is underway.

This is about updating the watchdog so that catalogs can be (temporarily) protected against being purged.

References: 

https://github.com/databrickslabs/ucx/blob/6a6f2f4dd2f3c37878dd3596a0ed202859afa650/src/databricks/labs/ucx/mixins/fixtures.py#L974

**Comment by JCZuurmond** [comment]
Issue for updating watchdog was already created: https://github.com/databrickslabs/watchdog/issues/54
