### ISSUE TITLE
[FEATURE] Let crawlers support `append` to tables

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2597]
### Summary

Let crawlers support `append` to tables

**Comment by JCZuurmond** [comment]
@asnare : What is the default `overwrite` or `append`?

**Comment by asnare** [comment]
> @asnare : What is the default `overwrite` or `append`?

@JCZuurmond: The default historically is:

 - Crawlers assume their table is empty and `append` records.
 - Some of the workflow tasks that can be re-run perform a `.reset()` prior to `.snapshot()` to ensure the prior assumption holds.

None of the crawlers perform incremental updates (whereby records are appended in batches): they gather everything and save it in a single operation.

PR #2566 updates this convention so that:

 - Crawlers no longer assume the table is empty.
 - The inventory is updated atomically using a single `overwrite` operation.

This change of semantics makes things a bit more robust:

 - During a re-run there is no interval when the table is empty between a reset and the subsequent append. (During this window, a concurrent read of the snapshot would trigger a parallel crawl.)
 - Concurrent crawls aren't supposed to happen, but if they do the results are now semantically correct instead of the records being duplicated due to the multiple appends.
 - Although a lot of the crawlers aren't _supposed_ to be re-run, if this happens we will no longer end up with duplicate records.
