### ISSUE TITLE
Create a job to self-update the installation of the project

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#274]
The job should:
- look up github releases
- get the latest tag
- download release tarball (or wheel)
- install the latest wheel on the job cluster (evaluate if this is possible)
- run the installer

**Comment by JCZuurmond** [comment]
This issue is interesting as we know users do not upgrade ucx regularly. Moreover, newer ucx versions provide more functionality and resolve issues, which is useful to UCX users.

However, it introduces a second installation path (with another context), thus there is a risk of creating a new set of bugs when this does not work

**Comment by gueniai** [comment]
Instead of installing the new version silently, we could warn customers that a newer version is available and that they should upgrade, and they would need to acknowledge the message somehow before continuing.

**Comment by nfx** [comment]
deferring to CLI
