### ISSUE TITLE
Allow disabling/skipping of workflow tasks via config

### ISSUE THREAD

**Issue by larsgeorge-db** [databrickslabs/ucx#283]
Some tasks in a workflow (here the group inventorizing) can take a long time but is not required for an assessment run. Add a config entry that allows to skip such tasks temproarily:

```
...
skip_tasks:
- crawl_grants
- crawl_mounts
```

**Comment by nfx** [comment]
We must not allow that, otherwise users will disable what prepares the important dataset and things will break unexpectedly.

There's "Repair Run" button in the workflows ui that restarts only the failed tasks. Probably that needs a documentation, as some users don't know about the feature.

If you want ad-hoc experimentation for a task, there's debug notebook

**Comment by larsgeorge-db** [comment]
This is not for repair runs, this is for advanced users that want to control the flow of jobs. Not all tasks are necessary given certain use-cases. We can leave this, if you prefer, undocumented and use this only under guidance.

**Comment by nfx** [comment]
What is the use-case? The flow of jobs is always static and in a certain required order.
