### ISSUE TITLE
Bundle jobs in an uber job

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#314]
To perform migration the user currently has to run individual jobs manually:
1. assessment
2. migrate-groups
3. migrate-groups-cleanup
4. destroy-schema

For better user experience, long term, it would be great if the user just have to run a single job instead of making a decision on which job to run and in which order.

**Comment by pohlposition** [comment]
This is by design.  They will mostly map to the steps at go/uc/upgrade and serve as checkpoints.

Each workflow needs some human interaction after running it.  To check the output, see which things need some manual intervention, and take action.

It's also likely that the same workflow will need to be run multiple times (like upgrade jobs) while iterating through exceptions, but the prior workflows will not.
