### ISSUE TITLE
Scan external Hive metastore and create inventory

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#317]
Many of our customers uses centralized external hive metastore (Glue, hosted sql DB etc.) instead of the Databricks managed workspace specific metastore.

We should have a way in UCX to scan and create an inventory of the external hive metastore. Create inventory of the all the objects and create assessment report for the external hive metastore (inventory similar to the databricks hosted HMS).

## Open questions:
- how to migrate access of users to this new catalog? By looking at the cluster permissions? 
- do we support Table ACLs for data stored in the external hive metastore?

**Comment by pohlposition** [comment]
There's nothing in our current process, that I'm aware of, that would prevent it from being used to crawl an external metastore.  We use the Spark Catalog API to ingest this data.

However there are a few considerations we should think of:
1) Connection to external metastores are either done through spark config or init scripts.  We should include some documentation or prompting to the user when creating the config.yaml file to capture these settings so that they can be included in our assessment run.

2) Our default schema to persist the inventory is "ucx".  If multiple workspaces are sharing the same external metastore, then they will each be overwriting whatever data is in that schema (if the default is not overriden).  We could fix this by some propting in the install script while creating the config.yaml file, or by including the workspace_id in the schema default, like "1234567890_ucx".

**Comment by nfx** [comment]
@pohlposition I wonder if we could parse those init scripts

**Comment by FastLee** [comment]
For now, I'll set up an optional configuration option.

**Comment by pohlposition** [comment]
> Can we have external acls in the external metastore?

Legacy TACLs are tied to a workspace; even if the workspace is connected to an external metastore.

So even if you run a GRANT statement on a table in Workspace A that is connected to an external metastore, there is nothing that will automatically syncronize that GRANT to Workspace B.  Customers have created custom scripts for this in the past.  This is one of the benefits of UC is that the GRANTs are centralized now for each table.

Alternatively, HMS Federation will allow us to register an external metastore in UC once, and then create one set of GRANT statements against it.

**Comment by pohlposition** [comment]
should we create a separate issue to parse the init script sand cluster configs and save relevant info to the inventory tables?

**Comment by zpappa** [comment]
@radhikaathalye-db

**Comment by dmoore247** [comment]
Spark Catalog API (`spark.catalog`) has his been historically very slow. I've used the other apis (show tables, or the Python API  / driver apis.) which are an order of magnitude or two faster.

**Comment by nfx** [comment]
released in https://github.com/databrickslabs/ucx/pull/400
