### ISSUE TITLE
[FEATURE]: Connect `_migrate_table_create_ctas` to `migrate-tables` workflow

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#332]
most of the code is done in:
- https://github.com/databrickslabs/ucx/pull/1434

Diff:
https://github.com/databrickslabs/ucx/blob/9cb9dbf05ba26d6905a53ebbf964f25ce1bddc09/src/databricks/labs/ucx/hive_metastore/table_migrate.py#L286-L299

Tasks:
- [x] Copy this table using CTAS
- [ ] Copy the Metadata with `CREATE TABLE ... LIKE ...`
- [ ] Skip tables as needed based on size threshold or an exception list
- [x] Update the source table with `upgraded_to` property
- [ ] Link it to the workflow as task

**Comment by pohlposition** [comment]
Can we split issues between MANAGED (step:managed tables) and EXTERNAL (step:sync tables).

This maps to go/uc/upgrade

**Comment by pohlposition** [comment]
I'm changing the name of this issue from:
[Migrate MANAGED and EXTERNAL non-Parquet/non-Delta tables](https://github.com/databrickslabs/ucx/issues/332)

to

[Migrate MANAGED non-Parquet/non-Delta tables](https://github.com/databrickslabs/ucx/issues/332)

because:
1. It separates the workstreams to align to upgrade steps
2. The focus on cloning is applicable to managed tables, but not external tables.

**Comment by pohlposition** [comment]
One additional consideration to make with Managed tables, which is different to external tables, is that it needs to be executed as much as possible as an atomic transaction:

BEGIN TRANSACTION
 1.  "Lock old table to prevent writes". (maybe stop a streaming job or something else)
 2.  Clone Table
 3. Update WRITE references to new table
 4. Update READ references to new table
 5. "DEPRECATE" old managed table - Revoke permissions; maybe rename it with a prefix or something
COMMIT TRANSACTION

This is to prevent data from being written to the old table while the upgrade is being performed.

Additionally, you want to prevent data from being written to the old table after you have upgraded to the new table.

**Comment by pohlposition** [comment]
One option we may want to provide customers is to convert the managed table into an external table first (still using HMS).

If that completes successfully, then that external table can be upgraded more easily using our external table upgrade process.

External tables are easier to upgrade because you can upgrade their metadata independent of the job.  You don't need to worry about the atomic transaction so much.
