### ISSUE TITLE
Report AWS Instance Profile to UC Storage Credentials (via query)

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#338]
We should automat migration ACLs based on Instance Profiles / Service Principals and other legacy security mechanisms

Related issues:
- https://github.com/databrickslabs/ucx/issues/100

**Comment by pohlposition** [comment]
As part of this, we should output a report that tells the user what to do on the AWS side for each IAM role to enable UC to assume it, by establishing the trust relationship:
https://docs.databricks.com/en/data-governance/unity-catalog/get-started.html#configure-a-storage-bucket-and-iam-role-in-aws

**Comment by zpappa** [comment]
# Background
As part of the migration effort, customers need to migrate policies tied to instance profiles to UC Storage Credentials.

# Pre-requisites
- Customer will need to provide an AWS account in order to get details about the AWS instance profiles attached? 
- OR the assumption is that an existing instance profile can perform these policy lookup operations

# Output
- Customer should be provided a report based on crawler inventory.
**aws_instance_profiles_to_be_migrated**
Field | Comment
| -- | -- |
instance_profile | the name of the instance profile
policy_json | generated policy json for an inline policy
policy_update_command | generated update command to update an existing policy or create based on the policy json

# Considerations
**Inline vs attached policy**
- If a policy is inline, we should generate a new IAM role JSON in the JSON field based on the inline policy
- If a policy is attached, i.e. an existing IAM role we should provide a command in the command field to establish a trust relationship with UC for assumption

**Comment by pohlposition** [comment]
relates to https://github.com/databrickslabs/ucx/issues/94

**Comment by pohlposition** [comment]
We have a list of Instance Profiles in the inventory.
 - Need to create a report / query (for assessment)
 - Need to include prescriptive next steps for AWS Admin
 - Need to create a new issue for mapping from old instance profile to new credential (customer may want to consolidate)

**Comment by dmoore247** [comment]
I don't exactly follow the request here, but I do have code to [crawl through instance profiles and policy documents.](https://github.com/dmoore247/permissions-graph/blob/main/extract-triples/roles.py)

Also [code to walk glue catalogs](https://github.com/dmoore247/permissions-graph/blob/main/extract-triples/glue.py)

**Comment by dmoore247** [comment]
@pohlposition @zpappa Is this to be added to the assessment report? This thing should be tagged as such.
Is this assignment to implement the crawler, or flesh out the details for all the steps?

**Comment by dmoore247** [comment]
Jobs to be done:

## Assessment:
1. add `crawl_instance_profiles`
>  enumerate every instance profile
>  enumerate permissions on every instance profile?
>  scrape instance profile text and policy document (if instance profile permissions exist)

3. add table `instance_profiles`
4. add detail report query `instance_profiles`

> Call out storage policy docs
> Call out other AWS policies docs (e.g. Kinesis, secrets, 234 other services)

6. add summary report query `instance_profile_summary`


## Migration:
1. Generate proposed IAM Role
2. Bonus, generate high level IAM role to cover multiple instance profiles

**Comment by pohlposition** [comment]
LGTM.  
Ultimately, the user is going to take this report and hand it to an AWS Admin who will run through them and establish a trust relationship as per our documentation (perhaps link to the documentation instructions).

If possible, it would be good to include the AWS Account ID, so that it can be easily passed to the AWS Admin.

I'd separate the Assessment (this issue) from the creation of CREDENTIAL; which can be tracked and developed separately.

**Comment by dmoore247** [comment]
Basic API scraping is complete along with dashboard entry.
Next *might* be boto3 access to Instance Profile text.
The aws account_id is part of every arn, maybe separate that out or do that in the generator code.

**Comment by zpappa** [comment]
All we should do here:

**For each instance profile**
1) Here's the terraform you can run
2) Here's the command you can run in aws sdk

**Comment by nfx** [comment]
reassigning to @FastLee
