### ISSUE TITLE
Migrate Azure Service Principals that access storage to UC Storage Credentials

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#339]
We should automate ACLs based on Instance Profiles / Service Principals and other legacy security mechanisms.

See the data collected in:
- https://github.com/databrickslabs/ucx/pull/764

Expected flow:

1. check all service principals in `azure_storage_account_info.csv`
2. check all storage credentials
3. see which service principals have matching storage credentials
4. report what credentials are missing
5. prompt-confirm creation of storage credential from service principal
7. give user three options: terraform config, invoke AWS CLI, pick an existing role, create via API

Related issues:
- https://github.com/databrickslabs/ucx/issues/100
- https://github.com/databrickslabs/ucx/issues/862

**Comment by zpappa** [comment]
This is much more complicated than it sounds

Policy is stored on accounts, not on the service principal in Azure, so we'd have to go to each account in order to build a managed identity credential that has access to the right resources.

We should think about whether or not this is worth pursuing.

**Comment by pohlposition** [comment]
This is an opportunity to enforce the best practice of using Managed Identities rather than continue using service principals

**Comment by qziyuan** [comment]
@nfx some questions on this issue:

1. When mapping the storage and permission, I see `_map_storage` is doing:
```python
for container in self._azurerm.containers(storage):
    for role_assignment in self._azurerm.role_assignments(str(container)):
```
Will this capture the role assignment defined in the storage account level? Would the [list role assignment api](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/list-for-resource?view=rest-authorization-2022-04-01&tabs=HTTP) on container list the role that is inherited from the storage account? 
2. `azure_storage_account_info.csv` contains all service principals that has owner, contributor or reader roles on external locations used in Databricks. However we don't know if such a service principal is allowed to be used in Databricks or not, we may need:
- Customer to manually confirm. But it will be a challenge for big customers with hundreds of storage account and service principals, such as AT&T.
- UCX to check if such a service principal is ever used in Databricks and provide such info to help the customer to make the decision. The SP crawler already checks many places, we should have good coverage here, except the session level spark config set inside notebook and code.
3. Am I right the `client_id` in `azure_storage_account_info.csv` may belongs to a managed identity, since both MI and SP will have `ServicePrincipal` as the `PrincipalType` in the list role assignment response? If so, we need to treat the separately, as SP need a client secret and MI need an access connector.
4. Most importantly, since we strongly recommend to create storage credential using MI (I even see the instruction is took out from the [public document](https://learn.microsoft.com/en-us/azure/databricks/archive/unity-catalog/service-principals#--create-a-storage-credential-that-uses-a-service-principal-legacy) and marked as [legacy here](https://learn.microsoft.com/en-us/azure/databricks/archive/unity-catalog/service-principals#--create-a-storage-credential-that-uses-a-service-principal-legacy)), should UCX create storage credential using service principal anymore? Should UCX create MI and access connector with the same role assignments the SP have?
@FastLee @zpappa @pohlposition welcome to chime in and comment here.

**Comment by nfx** [comment]
1. Yes

**Comment by nfx** [comment]
2. Customer to confirm

**Comment by nfx** [comment]
3. Yes, that's correct. But they can be matched by the same ID as presented in the storage credentials payload

**Comment by qziyuan** [comment]
Please see digraph below for what we currently have with recent PR and what are missing (dotted lines) for this issue. 
Please review if those dotted lines are making sense.
For service principal that are crawled by `azure/access.py` but not `assessment/azure.py`, we need to make a decision:
1. Ignore them as what we are doing now. So user need to create storage credentials and external locations by themselves.
2. Create a new client_secret and use it to create the storage credential.
3. Create access connector with system assigned managed identity that has same privilege as the service principal, and then create the storage credential.
![migrate sc ina zure-2024-02-28-190255](https://github.com/databrickslabs/ucx/assets/91635877/5118cb6d-1f1a-4196-9709-cbe5e7615cdc)
