### ISSUE TITLE
Delta Sharing is reported as incompatible with UC, even though it's meant for UC

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#789]
Incorrect assessment: `Non-DELTA format: DELTASHARING`

<img width="632" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/a0c48772-1580-4834-949b-d9921b2c17ca">

**Comment by larsgeorge-db** [comment]
This raises a question... how do we handle `DELTASHARING` table types? Fixing the condition in the view definition (which by the way was wrong already comparing the uppercase values from the `tables` table with a lowercase value `delta`) to handle this special table type results in it being treated as a DBFS Root table due to their path pointing to a `Fileshare` location. How are these handled during migration?

![image](https://github.com/databrickslabs/ucx/assets/136075433/0b9a6f3e-752a-4352-805c-587ea8c8cfb3)

![image](https://github.com/databrickslabs/ucx/assets/136075433/bb694e89-f0b3-4ac0-94d8-d96b84074668)
