### ISSUE TITLE
[FEATURE]: Migrate external tables not supported by the "sync" command

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Tables that are not one of the supported table format for the sync command are not currently migrated to UC.

Fine-grained:
- https://github.com/databrickslabs/ucx/issues/1340

Related issues:
- https://github.com/databrickslabs/ucx/issues/333
- https://github.com/databrickslabs/ucx/issues/670

### Proposed Solution

Allow users to migrate unsupported type, by converting these to Delta.

**Comment by qziyuan** [comment]
- Supported Spark DataSource by SYNC:
`Delta`, `Parquet`, `CSV`, `JSON`, `ORC`, `TEXT`, `AVRO`

- Not supported Spark DataSource by UC and SYNC:
`BINARYFILE`, `JDBC`, `LIBSVM`, custom implementation of `org.apache.spark.sql.sources.DataSourceRegister`

- All Hive Serde table are not supported by SYNC.

## Migration strategy:
| table.provider | Hive Serde(row format) and file format | migration strategy |
| --- | --- | --- |
| BINARYFILE | NA | 1. By default CTAS to Delta <br> 2. Prompt If user want to keep the original file format instead of writing their binary content into parquet file, if so do not migrate |
| JDBC | NA | 1. Do not migrate right now <br> 2. In the future, migrate to Lakehouse Federation, if no supported federation connector consider [view based solution](https://docs.google.com/document/d/1cNJHzMne65VpPVHYNKgcW9upDv8SzBzjbYQea706iPM/edit#heading=h.l4bcfrtx5kk)|
| LIBSVM | NA | Do not migrate |
| custom implementation of DataSourceRegister | NA | Do not migrate |
| HIVE | inputFormat=OrcInputFormat <br> outputFormat=OrcOutputFormat <br> serde=OrcSerde | 1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using ORC ... location ...` |
| HIVE | inputFormat=MapredParquetInputFormat <br> outputFormat=MapredParquetOutputFormat <br> serde=ParquetHiveSerDe | 1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using PARQUET ... location ...` |
| Hive | inputFormat=AvroContainerInputFormat <br> outputFormat=AvroContainerOutputFormat <br> serde=AvroSerDe | 1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using AVRO ... location ...` |
| Hive | inputFormat=SequenceFileInputFormat <br> outputFormat=SequenceFileOutputFormat <br> serde=LazySimpleSerDe | CTAS to Delta |
| Hive | inputFormat=RCFileInputFormat <br> outputFormat=RCFileOutputFormat <br> serde=LazyBinaryColumnarSerDe | CTAS to Delta |
| Hive | inputFormat=TextInputFormat <br> outputFormat=HiveIgnoreKeyTextOutputFormat <br> serde=LazySimpleSerDe | 1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using CSV ... location ...` need to get the field delimiter from HMS table metadata and set it accordingly in UC CSV table, also the disable quote |
| Hive | inputFormat=TextInputFormat <br> outputFormat=HiveIgnoreKeyTextOutputFormat <br> serde=RegexSerDe | CTAS to Delta |
| Hive | inputFormat=TextInputFormat <br> outputFormat=HiveIgnoreKeyTextOutputFormat <br> serde=JsonSerDe | 1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using JSON ... location ...` *need test* |
| Hive | inputFormat=TextInputFormat <br> outputFormat=HiveIgnoreKeyTextOutputFormat <br> serde=OpenCSVSerde |  1. By default CTAS to Delta. <br> 2. If user prefer in place upgrade and confirmed during installation, migrate with `create table ... using CSV ... location ...` |
| Hive | All other non native serdes | CTAS to Delta, if failed skip it |

## Changes required
1. Table crawler need to crawl hive serde and file format info.
2. Table class should store hive serde and file format info..

## Reference:
- Full Hive Serde class name for `orc`, `parquet`, `avro` can be found [here](https://src.dev.databricks.com/databricks/runtime@master/-/blob/sql/core/src/main/scala/org/apache/spark/sql/internal/HiveSerDe.scala?L45&subtree=true)
- More details of [OpenCSVSerde, JsonSerDe](https://cwiki.apache.org/confluence/display/hive/languagemanual+ddl#LanguageManualDDL-RowFormats&SerDe)

**Comment by nfx** [comment]
@qziyuan isn't table format already there?

**Comment by nfx** [comment]
It looks like we have to pre-empt this decision making into create_table_mapping CSV

**Comment by qziyuan** [comment]
> @qziyuan isn't table format already there?
@nfx For Hive Serde table, the current table format, derived from table.provider, will all be "HIVE". So we need extra info for serde, input/output format to differentiate them.

> It looks like we have to pre-empt this decision making into create_table_mapping CSV
We could either 

- make the decision during the installation, so the decision will be stored in config and we don't need to change table_mapping csv structure. But the decision will be global
- Or make the decision when create_table_mapping and add new field in the csv file to store the decision. In this way user is able to adjust the decision latter in table level by modifying the csv file.
